<?php
include ("local.php");
error_reporting(E_ALL);
$p = new aworkspage();
$sf = new scaffold("pedidos");
$p->addWidget(html::write("<h1>Bienvenid@</h1>"));
$d = new datagrid("pedido","pedido.php?");
$d->toolbar=false;
$sf->__query ="SELECT * FROM pedidos order by estado";
$d->objectField("idmodelo",new scaffold("modelos"),"referencia");
$d->objectField("idmadera",new scaffold("maderas"),"referencia");
$d->specialField("fecha","timestamp","date","html");
$d->headers("tipo_pedido","Tipo de Pedido");
$d->specialField("tipo_pedido","tipo_pedido","ooentity","tipowidget");
$d->headers("estado","Estado");
$d->headers("cliente","Cliente");
$d->headers("referencia","Referencia");
$d->hideField("observaciones");
$d->hideField("otro_material");
$d->specialField("estado","estado",ooentity,estadolistwidget);
$d->specialField("fecha_pedido","timestamp",date,html);
$d->specialField("fecha_entrega_prevista","timestamp",date,html);
$d->specialField("fecha_entrega","timestamp",date,html);
$d->headers("fecha_entrega","Fecha de Entrega");
$d->headers("fecha_entrega_prevista","Fecha de Entrega Prevista");
$d->headers("fecha_pedido","Fecha de Pedido");
$b = new Box("Pedidos en Cartera");
$d->drop($sf);
$t = new toolbar();
$t->addWidget(new button("A&ntilde;adir Pedido","pedido_add.php","add"));
$t->addWidget(new button("Gestionar Modelos","modelos.php","package"));
$t->addWidget(new button("Gestionar Maderas","maderas.php","map"));		
$b->addWidget($t);
$b->addWidget($d);
$p->addWidget($b);
$p->draw();
